version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak_data:/opt/keycloak/data/
    restart: always
    command:
      - "start-dev"