# version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    ports:
      - 8080:8080
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak_data:/opt/keycloak/data/
      - ./utils:/opt/keycloak/utils
    command:
      - "start-dev"